// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteTunnel(arg1:string):Promise<void>;

export function ReloadSnapshot():Promise<main.SnapshotResponse>;

export function SaveProfile(arg1:main.SaveProfileRequest):Promise<void>;

export function SaveTunnel(arg1:main.SaveTunnelRequest):Promise<void>;

export function Snapshot():Promise<main.SnapshotResponse>;

export function StartAll():Promise<Record<string, string>>;

export function StartTunnel(arg1:string):Promise<void>;

export function StopAll():Promise<void>;

export function StopTunnel(arg1:string):Promise<void>;
