// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteTunnel(arg1) {
  return window['go']['main']['App']['DeleteTunnel'](arg1);
}

export function ReloadSnapshot() {
  return window['go']['main']['App']['ReloadSnapshot']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveTunnel(arg1) {
  return window['go']['main']['App']['SaveTunnel'](arg1);
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}

export function StartAll() {
  return window['go']['main']['App']['StartAll']();
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function StopAll() {
  return window['go']['main']['App']['StopAll']();
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}
